#!/usr/bin/python3
def decorator_fun(original_fun):
    def wrapper_fun():
        return original_fun()
    return wrapper_fun

@decorator_fun
def display():
    print("Display Function Running")
    
display()
