#!/usr/bin/python3

n = int(input())
n = n**2

top = left = 0
bottom = right = (n -1)
x = 1
way = 0
series = []
while top <= bottom and left <= right and x <= n**2:
    l = []
    if way == 0:
        l = series[top]
        for i in range(left, right + 1):
            l.append(x)
            x+1
    way = (way + 1) % 4