#!/usr/bin/python3
l = [[2,4,6,8], [5,9,12,16], [2,11,5,9],[3,2,1,8]]
top = 0;
bottom = len(l) - 1
left = 0
right = len(l[0]) - 1
way = 0
while(top <= bottom and left <= right):
    if way == 0:
        for i in range(left, right + 1 ):
            print(l[top][i])
        top += 1
    elif way == 1:
        for i in range(top, bottom + 1 ):
            print(l[i][right])
        right -= 1
    elif way == 2:
        for i in range(right , left-1, -1):
            print(l[bottom][i])
        bottom -= 1;
    elif way == 3:
        for i in range(bottom , top -1 , -1):
            print(l[i][left])
        left += 1
    way = (way + 1) % 4
